package amata1219.parkour.ui;

public enum UIType {

	NORMAL_PARKOURS,
	SEGMENT_PARKOURS,
	BIOME_PARKOURS,
	UPDATE_PARKOURS,
	EXTEND_PARKOURS,
	LATEST_CHECKPOINTS,
	LAST_CHECKPOINTS,
	PARKOUR_CHECKPOINTS,
	MY_PROFILE,
	STATUS_BOARD_SETTINGS,
	BUY_HAT,
	WEAR_HAT;

}
